# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "21:37"
      timezone: "Europe/Warsaw"
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns:
          - "*"
