<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../../src/IcoDecoder.cs" Link="IcoDecoder.cs" />
    <Compile Include="../../src/IcoEncoder.cs" Link="IcoEncoder.cs" />
  </ItemGroup>
</Project>
