import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");
const output = join(publicDir, "portable.html");

const helperScripts = [
  "hardening.js",
  "privacy-guard.js",
  "logo-compat.js",
  "svg-normalize.js",
  "module-shapes.js",
  "style-picker.js",
  "corner-palette.js",
  "frame-presets.js",
  "svg-compat.js",
  "qr-raster.js",
  "qr-palette.js",
  "qr-output-plus.js",
  "qr-self-test.js",
  "barcode-formats.js",
  "barcode-assist.js",
  "barcode-options.js",
  "scanner-compat.js",
  "scanner-details.js",
];

const vendorScripts = [
  "vendor/qr-code-styling.js",
  "vendor/bwip-js-min.js",
  "vendor/zxing-wasm-reader.js",
];

const mime = (path) => path.endsWith(".woff2")
  ? "font/woff2"
  : path.endsWith(".wasm")
    ? "application/wasm"
    : "application/octet-stream";

const dataUri = async (relativePath) => {
  const bytes = await readFile(join(publicDir, relativePath));
  return `data:${mime(relativePath)};base64,${bytes.toString("base64")}`;
};

const inlineScript = (source) => source.replaceAll("</script", "<\\/script");

let html = await readFile(join(publicDir, "index.html"), "utf8");

html = html
  .replace(/<link\b[^>]*rel=["'](?:icon|mask-icon|apple-touch-icon|preconnect)["'][^>]*>\s*/gi, "")
  .replace(/<link\b[^>]*href=["']https:\/\/fonts\.googleapis\.com\/[^"']+["'][^>]*>\s*/gi, "");

let fonts = await readFile(join(publicDir, "fonts.css"), "utf8");
const fontRefs = [...fonts.matchAll(/url\(["']?\/fonts\/([^"')]+)["']?\)/g)];
for (const match of fontRefs) {
  fonts = fonts.replace(match[0], `url("${await dataUri(`fonts/${match[1]}`)}")`);
}
html = html.replace("</head>", `<style data-portable-fonts>\n${fonts}\n</style>\n</head>`);

for (const relativePath of vendorScripts) {
  const source = inlineScript(await readFile(join(publicDir, relativePath), "utf8"));
  const pattern = new RegExp(`<script\\s+src=["']/?${relativePath.replaceAll("/", "\\/")}["']\\s*><\\/script>`, "i");
  if (!pattern.test(html)) throw new Error(`missing script tag: ${relativePath}`);
  html = html.replace(pattern, `<script data-portable-source="${relativePath}">\n${source}\n</script>`);
}

const wasm = await dataUri("vendor/zxing_reader.wasm");
if (!html.includes('"vendor/zxing_reader.wasm"')) throw new Error("ZXing WASM locator not found");
html = html.replaceAll('"vendor/zxing_reader.wasm"', JSON.stringify(wasm));

const helpers = [];
for (const name of helperScripts) {
  helpers.push(`<script data-portable-source="${name}">\n${inlineScript(await readFile(join(publicDir, name), "utf8"))}\n</script>`);
}
html = html.replace("</body>", `${helpers.join("\n")}\n</body>`);

for (const forbidden of [
  /<script\b[^>]*\bsrc=/i,
  /<link\b[^>]*\brel=["']stylesheet["']/i,
  /fonts\.googleapis\.com/i,
  /vendor\/zxing_reader\.wasm/i,
]) {
  if (forbidden.test(html)) throw new Error(`portable output keeps external asset: ${forbidden}`);
}

await writeFile(output, `<!-- Generated by scripts/portable.mjs. Do not edit. -->\n${html}`);
console.log("Built public/portable.html");
